### PR TITLE
add listener for token timeout

### PR DESCRIPTION
**Pull request by janiseliang**
`onAuthStateChanged` only listens for sign-in and sign-out. instead, we can use `onIdTokenChanged` to listen for sign-in, sign-out, and token update after timeouts

https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onidtokenchanged

### CODE REVIEW

**Comment by janiseliang** [comment]
the token was getting updated in the userContext, but wasn't getting refreshed in the react component because we were copying `props.user` into `this.state.user` when we should have just been using `this.props.user` directly

**Comment by justinazhang** [comment]
> the token was getting updated in the userContext, but wasn't getting refreshed in the react component because we were copying `props.user` into `this.state.user` when we should have just been using `this.props.user` directly
> 
> should hoooopefully be fixed for good this time!


packingDetailed and bagPacking also use this.state.user sorry :( should i fix that?

**Comment by janiseliang** [comment]
> > the token was getting updated in the userContext, but wasn't getting refreshed in the react component because we were copying `props.user` into `this.state.user` when we should have just been using `this.props.user` directly
> 
> > 
> 
> > should hoooopefully be fixed for good this time!
> 
> 
> 
> 
> 
> packingDetailed and bagPacking also use this.state.user sorry :( should i fix that?

whoops i missed those, thanks! i can fix them and i'll also make sure none of the other pages use it

**Comment by justinazhang** [comment]
> > > the token was getting updated in the userContext, but wasn't getting refreshed in the react component because we were copying `props.user` into `this.state.user` when we should have just been using `this.props.user` directly
> > 
> > 
> > > 
> > 
> > 
> > > should hoooopefully be fixed for good this time!
> > 
> > 
> > packingDetailed and bagPacking also use this.state.user sorry :( should i fix that?
> 
> whoops i missed those, thanks! i can fix them and i'll also make sure none of the other pages use it

yay thank you sm!!

**Review by justinazhang — APPROVED** [review]
Yay looks good! Also tried this out during open hours and it worked flawlessly :D

**Comment by janiseliang** [comment]
> Yay looks good! Also tried this out during open hours and it worked flawlessly :D

yay!! we finally did it :)

**Pull request merged**
