### PR TITLE
convert datetime to strings before writing to sheets

### PR DESCRIPTION
**Pull request by janiseliang**
deals with the concurrency issue when we fail to reformat the date/time columns if two checkouts occur at the exact same time. does the reformatting on our side so we don't need the sheets API to do the reformatting

### CODE REVIEW

**Comment by janiseliang** [comment]
decided to just write as text instead of deleting a column and changing the format

the actual column is just written as a string now - @ethan-tam33 can you check that the data team can parse the stuff in the "test" tab of the checkout log? i think there shouldn't be any change on the other end but just wanted to confirm

**Comment by ethan-tam33** [comment]
> decided to just write as text instead of deleting a column and changing the format
> 
> the actual column is just written as a string now - @ethan-tam33 can you check that the data team can parse the stuff in the "test" tab of the checkout log? i think there shouldn't be any change on the other end but just wanted to confirm



> decided to just write as text instead of deleting a column and changing the format
> 
> the actual column is just written as a string now - @ethan-tam33 can you check that the data team can parse the stuff in the "test" tab of the checkout log? i think there shouldn't be any change on the other end but just wanted to confirm

Hey Janise! I'm looking at the checkout log, and there doesn't seem to be anything in the rows of the "test" tab. Do you mean everything under those columns in the future will be in string form?

**Comment by justinazhang** [comment]
LGTM!

**Review by justinazhang — APPROVED** [review]

**Comment by justinazhang** [comment]
> > decided to just write as text instead of deleting a column and changing the format
> > the actual column is just written as a string now - @ethan-tam33 can you check that the data team can parse the stuff in the "test" tab of the checkout log? i think there shouldn't be any change on the other end but just wanted to confirm
> 
> > decided to just write as text instead of deleting a column and changing the format
> > the actual column is just written as a string now - @ethan-tam33 can you check that the data team can parse the stuff in the "test" tab of the checkout log? i think there shouldn't be any change on the other end but just wanted to confirm
> 
> Hey Janise! I'm looking at the checkout log, and there doesn't seem to be anything in the rows of the "test" tab. Do you mean everything under those columns in the future will be in string form?

@ethan-tam33 Yeah exactly, so the date column of the "test" (and "Fall 22" once merged into main) tab  would look the same as how it looked previously, but now it'll just be stored as a plain string rather than a date object

**Pull request merged**
